# -*- coding: utf-8 -*-
"""csv con comas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7-zDNgAeQe_EfhD1Vq7goXZP8tPCidl
"""

import pandas as pd
import matplotlib.pyplot as plt

# Leer el archivo CSV
datos = pd.read_csv("Data.csv")

# Mostrar las primeras filas para verificar que se leyó correctamente
print(datos.head())
# Gráfica de velocidad angular
plt.figure(figsize=(8,5))
plt.plot(datos["Time (s)"], datos["Angular velocity (rad/s)"], marker="o")
plt.title("Velocidad Angular vs Tiempo")
plt.xlabel("Tiempo (s)")
plt.ylabel("Velocidad Angular (rad/s)")
plt.grid(True)
plt.show()

# Gráfica de aceleración
plt.figure(figsize=(8,5))
plt.plot(datos["Time (s)"], datos["Acceleration (m/s^2)"], marker="o")
plt.title("Aceleración vs Tiempo")
plt.xlabel("Tiempo (s)")
plt.ylabel("Aceleración (m/s²)")
plt.grid(True)
plt.show()
